# Tensors in pytorch
**this is a cheatsheet to use  tensor in pytorch**



*to learn pytorch in python It is  crucial to first learn about **tensors** and  see how we can work with them .*


***What is a Tensor?***

Tensors are simply mathematical objects that can be used to describe physical properties, just like scalars and vectors. In fact tensors are merely a generalisation of scalars and vectors; a scalar is a zero rank tensor, and a vector is a first rank tensor.



In [1]:
# first lets import the pytorch lib

import torch
torch.__version__


'2.1.0+cu121'

In [6]:

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
vector = torch.tensor([2 , 3 , 4])
vector

tensor([2, 3, 4])

In [9]:
# with the attribute ndim we can see how many dimension our vector has
vector.ndim

1

In [14]:
# now lets see the size or shape of our vector
vector.shape

torch.Size([3])

In [ ]:
MATRIX = torch.tensor([[1 , 2 , 3  ] ,
                       [4 , 5 , 6]])
MATRIX.shape

torch.Size([2, 3])

In [ ]:
TENSOR = torch.tensor([
                        [[1 , 2 , 3  , 4],
                         [5 , 6 , 7 , 8] ,
                         [9 , 10 ,11 ,12]] ,

                        [[-1 , -2 , -3  , -4],
                         [-5 , -6 , -7 , -8] ,
                         [-9 , -10 ,-11 ,-12]]
                        ])

TENSOR.shape

torch.Size([2, 3, 4])

In [ ]:
# Creat a random tenor
randomTensor = torch.rand(  2  ,3 , 4  )
randomTensor

tensor([[[0.3089, 0.7720, 0.9058, 0.2871],
         [0.8675, 0.2136, 0.8162, 0.7317],
         [0.3922, 0.2604, 0.8451, 0.1258]],

        [[0.2129, 0.5105, 0.8099, 0.9043],
         [0.6437, 0.0788, 0.3157, 0.7984],
         [0.7838, 0.7649, 0.0571, 0.7913]]])

In [ ]:
zeros = torch.zeros(2 ,3 , 4)
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

with **zeros_like** we can buil a zero tensor with the exact shape of another tensor that we have

In [16]:
torch.zeros_like(randomTensor)

NameError: name 'randomTensor' is not defined

In [ ]:
oneToTen = torch.arange(1 , 11)
oneToTen

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
tenZeros = torch.zeros_like(oneToTen)
tenZeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

tensor Datatype

In [ ]:
randomTensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([1 , 2 ,3 , 4 ] , dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_32_tensor = float_16_tensor.type(torch.float32)
float_32_tensor.dtype

torch.float32

now lets learn more about tensor operations

In [ ]:
tensor = torch.tensor([1 , 2 , 3])
print(tensor + 10)
print(tensor * 10)
print(tensor / 10)
print(tensor - 10)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])
tensor([-9, -8, -7])


In [ ]:
# also we can use another method to calculate
print(torch.add(tensor , 10))
print(torch.mul(tensor , 10))
print(torch.divide(tensor , 10))
print(torch.sub(tensor , 10))

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])
tensor([-9, -8, -7])


In [ ]:
tensor2 = torch.tensor([[1 , 2] ,
                        [3 , 4]])

In pytorch you can also utilize different types of multiplication for matrices|

In [17]:
# normal muliplication
print(tensor.mul(tensor))
# cross fuction
print(tensor2.matmul(tensor2))
#dot function
print(tensor.dot(tensor))


NameError: name 'tensor' is not defined

In [ ]:
#adding the diagonal valus (known as trace in math)
torch.trace(tensor2)

tensor(5)

In [ ]:
#teranspose a matrix(changing rows to columns & columns to rows)
torch.t(tensor2)

tensor([[1, 3],
        [2, 4]])

In [ ]:
%time
matrix = torch.rand(size=(10 , 10) , dtype=torch.float32)

# Calculate the determinant using torch.det()
torch.det(matrix)


CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 8.11 µs


tensor(-0.0114)

In [ ]:
tensor = torch.arange(0 , 200 , 20 , dtype=torch.float32)
tensor

tensor([  0.,  20.,  40.,  60.,  80., 100., 120., 140., 160., 180.])

**maximum  , minimum ,  average  , median and standard deviation in pytorch**

In [ ]:
torch.max(tensor)  , torch.min(tensor)

(tensor(180.), tensor(0.))

In [ ]:
tensor.max() , tensor.min()

(tensor(180.), tensor(0.))

In [ ]:
torch.mean(tensor)  , tensor.mean()

(tensor(90.), tensor(90.))

In [ ]:
torch.median(tensor)  , tensor.median()

(tensor(80.), tensor(80.))

In [ ]:
torch.std(tensor) , tensor.std()

(tensor(60.5530), tensor(60.5530))

In [ ]:
#finding the position
tensor2[0]

tensor([1, 2])

In [26]:
tensor = torch.tensor([[1, 3, 5],
                       [2, 8, 4]])

# Find the index of the maximum value along a specific axis (e.g., axis=1 for rows)
max_indices = torch.argmax(tensor, dim=1)

# Feel free to change  ( dim ) to see how the result will change

print(max_indices)

tensor([2, 1])


**reshaping , stacking , squeezing and unsqueezing tensor**


In [30]:
x = torch.arange(1. , 10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [31]:
x_reshaped = x.reshape(3 , 3)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [32]:
y = torch.arange(1 , 25)
y , y.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20, 21, 22, 23, 24]),
 torch.Size([24]))

In [33]:
y_reshaped = y.reshape(2 ,3 , 4)
y_reshaped , y_reshaped.shape

(tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],
 
         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]]),
 torch.Size([2, 3, 4]))

In [34]:
#view

z = x.view(3 ,3 )
z , z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

difference between view and reshape :

In [35]:
#changing z changes  x (because a view of a tensor share the same memory as the  original)
z[0 , 0] = 404
z , x

(tensor([[404.,   2.,   3.],
         [  4.,   5.,   6.],
         [  7.,   8.,   9.]]),
 tensor([404.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]))

In [36]:
# now we redefine the x
x = torch.arange(1. , 13.)
x , x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [37]:
Q = x.reshape(3 ,4 )
Q

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [38]:
t = torch.arange(11 , 23)
t = t.reshape(3 , 4)

In [39]:
#stacking a tensors on top of each other
x_stacked = torch.stack([Q ,t ,Q ] , dim=0)
x_stacked , x_stacked.shape


(tensor([[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.]],
 
         [[11., 12., 13., 14.],
          [15., 16., 17., 18.],
          [19., 20., 21., 22.]],
 
         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.]]]),
 torch.Size([3, 3, 4]))

In [40]:
x_stacked = torch.stack([Q ,t , Q ] , dim=1)
x_stacked , x_stacked.shape

(tensor([[[ 1.,  2.,  3.,  4.],
          [11., 12., 13., 14.],
          [ 1.,  2.,  3.,  4.]],
 
         [[ 5.,  6.,  7.,  8.],
          [15., 16., 17., 18.],
          [ 5.,  6.,  7.,  8.]],
 
         [[ 9., 10., 11., 12.],
          [19., 20., 21., 22.],
          [ 9., 10., 11., 12.]]]),
 torch.Size([3, 3, 4]))

In [ ]:
x_stacked = torch.stack([Q ,t ,Q ] , dim=2)
x_stacked , x_stacked.shape

(tensor([[[ 1., 11.,  1.],
          [ 2., 12.,  2.],
          [ 3., 13.,  3.],
          [ 4., 14.,  4.]],
 
         [[ 5., 15.,  5.],
          [ 6., 16.,  6.],
          [ 7., 17.,  7.],
          [ 8., 18.,  8.]],
 
         [[ 9., 19.,  9.],
          [10., 20., 10.],
          [11., 21., 11.],
          [12., 22., 12.]]]),
 torch.Size([3, 4, 3]))

In [45]:
#squeezing  a tensor to get rid of single dim
x = torch.zeros(2, 1, 2, 1, 2)
print(f" \n  the size of the tensor is : {x.size()}")
y = torch.squeeze(x)
print(f" \n ather the squeez(x) we 'll remove all single dimentions :{y.shape} ")
y = torch.squeeze(x, 0)
print(f" \n  if we specify the first dimention because the its 2 it will stay the same :{y.shape} ")
y = torch.squeeze(x, 1)
print(f" \n if we specify the third dim to be squeezed just the third will squeezed :{y.shape} ")
y = torch.squeeze(x, ( 2 , 3))
print(f" \n  and we can set a list of dims to get sqeezed:{y.shape} ")



 
  the size of the tensor is : torch.Size([2, 1, 2, 1, 2])
 
 ather the squeez(x) we 'll remove all single dimentions :torch.Size([2, 2, 2]) 
 
  if we specify the first dimention because the its 2 it will stay the same :torch.Size([2, 1, 2, 1, 2]) 
 
 if we specify the third dim to be squeezed just the third will squeezed :torch.Size([2, 2, 1, 2]) 
 
  and we can set a list of dims to get sqeezed:torch.Size([2, 1, 2, 2]) 


In [ ]:
# unsqueeze will add a 1 dim
x = torch.arange(1 ,9)
y = torch.unsqueeze(x , 0)
print(x , x.shape)
print(y , y.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8]) torch.Size([8])
tensor([[1, 2, 3, 4, 5, 6, 7, 8]]) torch.Size([1, 8])


In [ ]:
# for changing the order of the dimantions without changing the structure we can use permute
x = torch.arange(1 , 25).reshape(3 ,4 , 2)
y = torch.permute(x , (2 , 0  ,1 ))
print(x.shape)
print(y.shape)

torch.Size([3, 4, 2])
torch.Size([2, 3, 4])


In [ ]:
#keep in mind that the value of the .reshape and .permute will be different

t = x.reshape(2 ,3 , 4)
print(y.shape)
print(t.shape)
y ,"-------" , t

torch.Size([2, 3, 4])
torch.Size([2, 3, 4])


(tensor([[[ 1,  3,  5,  7],
          [ 9, 11, 13, 15],
          [17, 19, 21, 23]],
 
         [[ 2,  4,  6,  8],
          [10, 12, 14, 16],
          [18, 20, 22, 24]]]),
 '-------',
 tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],
 
         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]]))

interaction between numpy.array and tensor

In [51]:
import numpy as np

In [ ]:
array = np.arange(1 , 10  , dtype= np.float32)
tensor = torch.from_numpy(array)
type(array) , type(tensor)

(numpy.ndarray, torch.Tensor)

In [ ]:
array.dtype , tensor.dtype

(dtype('float32'), torch.float32)

In [49]:

tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

# Convert tensor to NumPy array
numpy_array = tensor.numpy()


print(tensor)

print(numpy_array)
type(numpy_array)

tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [53]:
numpy_array = np.array([[1, 2, 3],
                        [4, 5, 6]])

# Convert NumPy array to PyTorch tensor
tensor = torch.from_numpy(numpy_array)


print(numpy_array)

print(tensor)


[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])
